### ISSUE TITLE
Migrator won't work Ef Core 3.1.1

### ISSUE THREAD

**Issue by stopcorp** [phongnguyend/Practical.CleanArchitecture#24] opened 2020-01-23 17:06 UTC
Hello,

i created a simple docker mssql image 

https://stackoverflow.com/questions/45712122/connection-string-for-sqlserver-in-docker-container

it won't work. only the idsv tables (because of the included script of identityserver4 v 2.2.3-servicing-35854)

any idea? does the code work? No tables are generated (not from console or start from vs 2019)

Greetz
Stephan

**Comment by phongnguyend** [comment] 2020-01-24 03:50
Thanks @stopcorp for being interested in my experimental repository ^^!

This project was started as a place where I can do some experimental works related to .Net technologies in my free time, so It doesn't have lot documentation . I didn't think It interests people.

I've just added few guidelines which you can find in the README file at the root of the repository, please take a look and follow the instruction so that you will be able to run it on your own.

Feel free to let me know if you still face any issues running it.

**Comment by phongnguyend** [comment] 2020-01-24 03:51
Duplicate of #23

**Comment by stopcorp** [comment] 2020-01-24 16:48
This worked. But only from the Console. Not from starting inside VS 2019. Thx

**Closed** 2020-02-06 12:13 UTC
