### ISSUE TITLE
After five continuous http request for the same API getting delayed response. 

### ISSUE THREAD

**Issue by aneesanp123** [phongnguyend/Practical.CleanArchitecture#104] opened 2021-07-22 04:28 UTC
After five continuous(not an asynchronous each request having 30 seconds gap) http request for the same API getting delayed response. I am using angular. The request not reaching to the Controller also.

**Comment by phongnguyend** [comment] 2022-12-20 15:35
Close this for now as cannot reproduce.

**Closed by phongnguyend** 2022-12-20 15:35 UTC
